version: '3.8'
services:
  backend1:
    build: .
    environment:
      - INSTANCE_ID=1

  backend2:
    build: .
    environment:
      - INSTANCE_ID=2

  backend3:
    build: .
    environment:
      - INSTANCE_ID=3

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:81"
      - "8080:80"
    depends_on:
      - backend1
      - backend2
      - backend3