events {}

stream {
    upstream backend_pool_l4 {
        server backend1:8000;
        server backend2:8000;
        server backend3:8000;
    }

    server {
        listen 81;
        proxy_pass backend_pool_l4;
    }
}


http {
    upstream backend_pool {
        server backend1:8000;
        server backend2:8000;
        server backend3:8000;
    }

    server {
        listen 80;
        location /special {
            proxy_pass http://backend2:8000;   # always force instance 2
        }

        location / {
            proxy_pass http://backend_pool;    # normal round robin
        }
    }
}